server:
  port: 8081
  servlet:
    context-path: '/welcome' 
spring:
  application:
    name: 'first-service'
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress : true

    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        

